### ISSUE TITLE
Theme error: sphinx `html_js_files` configuration is not supported

### ISSUE THREAD

**Issue by theko2fi** [ansible-community/antsibull-docs#236] opened 2024-01-18 23:55 UTC
Hi everybody!

It seems like antsibull-docs or sphinx-ansible-theme doesn't support the `html_js_files` configuration option.

```bash
  Theme error:
  An error happened in rendering the page environment_variables.
  Reason: IsADirectoryError(21, 'Is a directory')
  writing output... [ 25%] environment_variables
```

I get the error above when trying to use it. Let me explain.

I use `antsibull-docs` (thanks for this tool ❤️ ) to build an online documentation for a collection. To track the stats for that documentation, I need to place the following code in the \<head>...\</head> section of each HTML page generated by antsibull-docs:
`<script defer src="https://eu.umami.is/script.js" data-website-id="xxxxxxxxxxxxxxxxxxxxxx"></script>`

Based on [sphinx documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html), the `html_js_files` configuration should do the trick. The code below should be placed in sphinx “build configuration file” (`conf.py`):
`html_js_files=[('https://eu.umami.is/script.js', {'data-website-id': 'xxxxxxxxxxxx','defer': 'defer'})]`

Since sphinx `conf.py` file is generated under the hood by `antsibull-docs` and extra configurations seem to be supported, then I added the code below to my workflow file:

```
init-extra-html-theme-options: |
   documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/branch/main/
init-extra-conf: "html_js_files=[('https://eu.umami.is/script.js', {'data-website-id': 'xxxxxxxxxxxxxxx','defer': 'defer'})]"
```

Unfortunately, it results in the error pasted at the beginning of this write-up. I'm not sure where's the root cause. Can someone tell me what's going on?

- The full GitHub actions workflow file is available at: https://github.com/theko2fi/ansible-multipass-collection/blob/61fa660dddb171b2157db40494612137d432648e/.github/workflows/docs-push.yml
- The full log is available at: https://github.com/theko2fi/ansible-multipass-collection/actions/runs/7562640828/job/20593503094

**Comment by felixfontein** [comment] 2024-01-19 07:43
I don't think antsibull-docs has anything to do with that. It just creates the RST files and `conf.py`. If it's the theme, it's more likely the sphinx-rtd-theme (https://sphinx-rtd-theme.readthedocs.io/en/stable/) on which the Ansible sphinx theme is based. Looking at it's source, it's likely not doing anything with it either. It seems to be Sphinx itself that handles these completely by itself. I'm out of time now, I'll try to look a bit more into this later.

**Comment by felixfontein** [comment] 2024-01-19 12:27
I've tried running this locally (after looking through a lot of code, which looked good). The problem is the conf.py addition:
```
html_js_files = "[('https://eu.umami.is/script.js', {'data-website-id': '2d66a652-7cca-4398-8c5a-d9b04a0d3a95','defer': 'defer'})]"
```
As you can see, there are quotes around everything. Which makes Sphinx treat this as a list of quite a few JS files, everyone with a one-letter filename :)

(On my machine, the JS filename `/` triggered the actual error.)

The docs building GHA action passes these options as `--extra-conf` to antsibull-docs (https://github.com/ansible-community/github-docs-build/blob/main/actions/ansible-docs-build-init/action.yml#L160). The documentation (`antsibull-docs sphinx-init --help`) for that option shows:

> Add additional configuration entries to the generated conf.py. Use the syntax `key=value` to add an entry `key = "value"`.

So yeah, this won't work as you want it to. (That option was meant to be able to add values with proper string escaping, not to simply append raw data.) I guess the documentation of the action / shared workflow could be improved to be more clear on what happens. And having an option to simply add arbitrary text at the bottom of `conf.py` would be nice for your use-case. (CC @briantist)

**Comment by felixfontein** [comment] 2024-01-19 20:44
I created a PR which allows to do this with the GHA action/workflows: https://github.com/ansible-community/github-docs-build/pull/73

**Comment by theko2fi** [comment] 2024-01-19 21:26
Thanks sooo much for all the time you dedicated to this issue, from searching the root cause to submitting this PR. I will give it a try right away. You're the MAN.

**Comment by felixfontein** [comment] 2024-01-20 11:41
@theko2fi thanks! I've merged the PR so you should be able to use the new `init-append-conf-py` option (for the shared workflows) from how on. If it doesn't work for some reason, please write in https://github.com/ansible-community/github-docs-build/pull/73 or here.

**Closed** 2024-01-20 11:40 UTC
